/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thoughtworks.training;
import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.*;

public class NumberProcessorTest {
//    @Test public void testAppHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//    }

//    @Test
//    public void testshouldreturn0(){
//        assertThat(new NumberProcessor().process("1 2 3 4 5"),is("3 5 7"));
//    }

}
